const bcrypt = require('bcryptjs');

const now = new Date().toISOString();
const demoPasswordHash = bcrypt.hashSync('demo123', 10);

const seedData = {
  users: [
    {
      id: 'user_farmer_amina',
      fullName: 'Amina Wanjiku',
      email: 'amina@mkulima.demo',
      passwordHash: demoPasswordHash,
      role: 'farmer',
      location: 'Nyeri',
      phone: '+254700111222',
      bio: 'Vegetable farmer focused on fresh weekly harvests.',
      createdAt: now,
    },
    {
      id: 'user_farmer_kiptoo',
      fullName: 'Kiptoo Cheruiyot',
      email: 'kiptoo@mkulima.demo',
      passwordHash: demoPasswordHash,
      role: 'farmer',
      location: 'Eldoret',
      phone: '+254700333444',
      bio: 'Bulk grain supplier serving retailers and millers.',
      createdAt: now,
    },
    {
      id: 'user_buyer_njeri',
      fullName: 'Njeri Muthoni',
      email: 'njeri@buyer.demo',
      passwordHash: demoPasswordHash,
      role: 'buyer',
      location: 'Nairobi',
      phone: '+254700555666',
      bio: 'Procures produce for a neighbourhood grocery.',
      createdAt: now,
    },
  ],
  products: [
    {
      id: 'product_tomatoes_01',
      sellerId: 'user_farmer_amina',
      name: 'Fresh Tomatoes',
      category: 'Vegetables',
      quantity: 120,
      unit: 'kg',
      pricePerUnit: 95,
      location: 'Nyeri',
      description: 'Vine-ripened tomatoes harvested this week.',
      available: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'product_kales_01',
      sellerId: 'user_farmer_amina',
      name: 'Sukuma Wiki',
      category: 'Leafy Greens',
      quantity: 80,
      unit: 'bunch',
      pricePerUnit: 35,
      location: 'Nyeri',
      description: 'Packed in clean bunches and ready for market.',
      available: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'product_maize_01',
      sellerId: 'user_farmer_kiptoo',
      name: 'Dry Maize',
      category: 'Grains',
      quantity: 300,
      unit: 'bag',
      pricePerUnit: 4200,
      location: 'Eldoret',
      description: 'Well-dried 90kg bags suitable for wholesale purchase.',
      available: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'product_beans_01',
      sellerId: 'user_farmer_kiptoo',
      name: 'Rosecoco Beans',
      category: 'Legumes',
      quantity: 90,
      unit: 'kg',
      pricePerUnit: 180,
      location: 'Eldoret',
      description: 'Sorted, clean beans ideal for retailers and restaurants.',
      available: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  orders: [
    {
      id: 'order_demo_01',
      productId: 'product_tomatoes_01',
      buyerId: 'user_buyer_njeri',
      sellerId: 'user_farmer_amina',
      quantity: 20,
      totalAmount: 1900,
      paymentMethod: 'M-Pesa',
      status: 'confirmed',
      note: 'Deliver on Tuesday morning if possible.',
      createdAt: now,
      updatedAt: now,
    },
  ],
  messages: [
    {
      id: 'message_demo_01',
      conversationId: 'conversation_user_buyer_njeri_user_farmer_amina',
      participants: ['user_buyer_njeri', 'user_farmer_amina'],
      senderId: 'user_buyer_njeri',
      receiverId: 'user_farmer_amina',
      body: 'Hi Amina, can you reserve 20kg of tomatoes for next week?',
      createdAt: now,
    },
    {
      id: 'message_demo_02',
      conversationId: 'conversation_user_buyer_njeri_user_farmer_amina',
      participants: ['user_buyer_njeri', 'user_farmer_amina'],
      senderId: 'user_farmer_amina',
      receiverId: 'user_buyer_njeri',
      body: 'Yes, I can prepare that order and confirm after harvest.',
      createdAt: now,
    },
  ],
};

module.exports = { seedData };
